template = "https://github.com/giellalt/template-lang-und"
rev_id = 280
template_sha = "6beee360d8349c39749ac477719ead241493924c"

[replacements]
__GLOTTOLOG_ID__ = "voti1245"
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
