template = "https://github.com/giellalt/template-lang-und"
rev_id = 119
template_sha = "37d664326547737c40736d66568df3412cb835ab"

[replacements]
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
