template = "https://github.com/giellalt/template-lang-und"
rev_id = 137
template_sha = "802fd8b83bce294556e943c19a2dbfbeab559298"

[replacements]
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
