template = "https://github.com/giellalt/template-lang-und"
rev_id = 182
template_sha = "f80fba75feb60cb50b4820ba42e899f49030b5d6"

[replacements]
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
