template = "https://github.com/giellalt/template-lang-und"
rev_id = 185
template_sha = "ab0921ee1e75a04739e82be4750888e8da80f1db"

[replacements]
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
