template = "https://github.com/giellalt/template-lang-und"
rev_id = 188
template_sha = "039269192c86bc4e92e4de05023c97b6fa16b3e5"

[replacements]
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
