template = "https://github.com/giellalt/template-lang-und"
rev_id = 107
template_sha = "2f2f1f21a10b56b75f0c8afcf409f313674887bc"

[replacements]
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
