template = "https://github.com/giellalt/template-lang-und"
rev_id = 178
template_sha = "0e977ab51a115099656def83b47120d28edcd023"

[replacements]
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
