template = "https://github.com/giellalt/template-lang-und"
rev_id = 132
template_sha = "c9b931f62e94149b088c740ef7565270a9ed98e5"

[replacements]
__REPO__ = "lang-vot-x-ext-kkankain"
__UND2C__ = "vot"
__UNDEFINED__ = "Votic"
__UND__ = "vot"
